name: Deploy static site to Azure Storage

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload site to $web
        run: |
          pwd
          ls -la
          az storage blob upload-batch \
            --account-name marcuscloudresume \
            --auth-mode login \
            --destination '$web' \
            --source "${{ github.workspace }}"

      - name: Logout
        run: az logout || true
        if: always()
